name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # 3️⃣ Install Python deps (including pandas)
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Run backend tests
      - name: Run Python tests
        working-directory: backend
        env:
          PYTHONPATH: ${{ github.workspace }}/backend
        run: |
          pytest --cov=api --cov-report=term-missing --cov-fail-under=80

      # 5️⃣ Setup Node for front-end
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 6️⃣ Install front-end deps
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      # 7️⃣ Build front-end
      - name: Build frontend
        working-directory: frontend
        run: npm run build
